name: Tests
on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: latest
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - run: uv sync
      - run: uv run pytest --cov=algo_vault --cov-report=term-missing