name: Type Check
on: [ push, pull_request ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: latest
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - run: uv sync
      - run: uv run mypy src/ --strict --install-types --non-interactive